import { DeployFunction } from "hardhat-deploy/types";
import * as fs from "fs";
import path from "path";
import prettier from "prettier";
import type { HardhatRuntimeEnvironment } from "hardhat/types";
import { agoraFrontendContractsDir } from "../utils/paths";

const GENERATED_COMMENT = `
/**
 * This file is autogenerated by the hardhat deploy sync script.
 * Do not edit manually.
 */
`;

const DEPLOYMENTS_DIR = "./deployments";

function getDirectories(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);
}

function getContractNames(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter(dirent => dirent.isFile() && dirent.name.endsWith(".json"))
    .map(dirent => dirent.name.split(".")[0]);
}

/**
 * Build `deployedContracts.ts` from `deployments/<network>/*.json` only.
 * ABI + address come from hardhat-deploy artifacts; `inheritedFunctions` is left empty
 * unless we later reintroduce scaffold-eth source tracing.
 */
function collectContractsByChain() {
  if (!fs.existsSync(DEPLOYMENTS_DIR)) {
    throw new Error("No deployments directory found. Run deploy first.");
  }
  const output = {} as Record<string, any>;
  for (const chainName of getDirectories(DEPLOYMENTS_DIR)) {
    const chainIdFile = `${DEPLOYMENTS_DIR}/${chainName}/.chainId`;
    if (!fs.existsSync(chainIdFile)) continue;
    const chainId = fs.readFileSync(chainIdFile).toString();
    const contracts = {} as Record<string, any>;
    for (const contractName of getContractNames(`${DEPLOYMENTS_DIR}/${chainName}`)) {
      const deployment = JSON.parse(fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/${contractName}.json`).toString());
      contracts[contractName] = {
        address: deployment.address,
        abi: deployment.abi,
        inheritedFunctions: {},
        deployedOnBlock: deployment.receipt?.blockNumber,
      };
    }
    output[chainId] = contracts;
  }
  return output;
}

const syncFrontendContracts: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const targetDir = agoraFrontendContractsDir(hre);
  const allContracts = collectContractsByChain();
  const fileContent = Object.entries(allContracts).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }
  const outFile = path.join(targetDir, "deployedContracts.ts");
  fs.writeFileSync(
    outFile,
    await prettier.format(
      `${GENERATED_COMMENT}\nexport const deployedContracts = {${fileContent}} as const;\n\nexport type DeployedContractsMap = typeof deployedContracts;\n`,
      { parser: "typescript" },
    ),
  );
  console.log(`📝 Updated TypeScript contract definition file at ${outFile}`);
};

export default syncFrontendContracts;
syncFrontendContracts.tags = ["sync-frontend"];
