"""
Generated contract metadata consumed by the Python backend.

The manifest.json file is generated by the Hardhat deploy pipeline
(packages/hardhat/deploy/98_generate_backend_contracts.ts) and contains
ABIs, deployed addresses per network, and pre-computed relayer selectors.

Usage:
    from app.contracts import load_abi, get_address, get_relayer_selectors
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_MANIFEST_PATH = Path(__file__).parent / "manifest.json"


@lru_cache(maxsize=1)
def _load_manifest() -> dict[str, Any]:
    if not _MANIFEST_PATH.exists():
        raise FileNotFoundError(
            f"Contract manifest not found at {_MANIFEST_PATH}. "
            "Run `yarn deploy` from the repo root to generate it."
        )
    with open(_MANIFEST_PATH) as f:
        return json.load(f)


def load_abi(contract_name: str, chain_id: str | None = None) -> list[dict[str, Any]]:
    """Return the ABI for a contract. Searches all networks if chain_id is None."""
    manifest = _load_manifest()
    for cid, net in manifest["networks"].items():
        if chain_id and cid != str(chain_id):
            continue
        entry = net["contracts"].get(contract_name)
        if entry:
            return entry["abi"]
    raise KeyError(f"Contract {contract_name!r} not found in manifest (chain_id={chain_id})")


def get_address(contract_name: str, chain_id: str) -> str:
    """Return the deployed address for a contract on a specific network."""
    manifest = _load_manifest()
    net = manifest["networks"].get(str(chain_id))
    if not net:
        raise KeyError(f"Network chain_id={chain_id} not found in manifest")
    entry = net["contracts"].get(contract_name)
    if not entry:
        raise KeyError(f"Contract {contract_name!r} not found on chain_id={chain_id}")
    return entry["address"]


def get_relayer_selectors() -> set[str]:
    """Return the set of allowed 4-byte function selectors for the relayer."""
    manifest = _load_manifest()
    return {entry["selector"].lower() for entry in manifest["relayerAllowedSelectors"]}


def get_relayer_selector_details() -> list[dict[str, str]]:
    """Return selector entries with name, selector, and contract for debugging."""
    manifest = _load_manifest()
    return manifest["relayerAllowedSelectors"]


def available_networks() -> list[str]:
    """Return chain IDs that have deployments in the manifest."""
    manifest = _load_manifest()
    return list(manifest["networks"].keys())


def available_contracts(chain_id: str) -> list[str]:
    """Return contract names deployed on a specific network."""
    manifest = _load_manifest()
    net = manifest["networks"].get(str(chain_id))
    if not net:
        return []
    return list(net["contracts"].keys())
